# Site settings
title: 이정원
motto: FORK THE WORLD
email: madlymissyou@gmail.com
description: # this means to ignore newlines until "baseurl:"
  이정원의 블로그
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://madlymissyou.github.io" # the base hostname & protocol for your site
twitter_username: madlymissyou
github_username:  madlymissyou

# Build settings
#markdown: redcarpet
#markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

excerpt_separator: <!--readmore-->
permalink: /:year/:month/:day/:title

gems:
  - jemoji